// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdMYVXfmfmJS_LKv7SxxgKez52H5PSkM',
    appId: '1:719827327864:web:c3fa68506bb680f2d7468d',
    messagingSenderId: '719827327864',
    projectId: 'guide237-94034',
    authDomain: 'guide237-94034.firebaseapp.com',
    storageBucket: 'guide237-94034.appspot.com',
    measurementId: 'G-EL47NL0NE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZu9xt0OLK_dYWiA9nkOsNAYxbE3nV4Ao',
    appId: '1:719827327864:android:fcc08718853c0f2ed7468d',
    messagingSenderId: '719827327864',
    projectId: 'guide237-94034',
    storageBucket: 'guide237-94034.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2DdWdChDtjToZm3_a1lMvOHESU11q4yo',
    appId: '1:719827327864:ios:5d501a04ae03ce3fd7468d',
    messagingSenderId: '719827327864',
    projectId: 'guide237-94034',
    storageBucket: 'guide237-94034.appspot.com',
    iosBundleId: 'com.example.simpleFlutterCinetpayTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2DdWdChDtjToZm3_a1lMvOHESU11q4yo',
    appId: '1:719827327864:ios:5d501a04ae03ce3fd7468d',
    messagingSenderId: '719827327864',
    projectId: 'guide237-94034',
    storageBucket: 'guide237-94034.appspot.com',
    iosBundleId: 'com.example.simpleFlutterCinetpayTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpdMYVXfmfmJS_LKv7SxxgKez52H5PSkM',
    appId: '1:719827327864:web:2b22b8f4937af4d4d7468d',
    messagingSenderId: '719827327864',
    projectId: 'guide237-94034',
    authDomain: 'guide237-94034.firebaseapp.com',
    storageBucket: 'guide237-94034.appspot.com',
    measurementId: 'G-PM6JBBXBRD',
  );
}
