name: simple_flutter_cinetpay_test
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.4.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_database: ^11.0.4
  http: ^1.2.2
  webview_flutter: ^3.0.4
dev_dependencies:
  intl: ^0.19.0
  test: ^1.25.2
